#!/usr/bin/env python3
import subprocess
import os
import time
import threading
import argparse

# Parse arguments
argparser = argparse.ArgumentParser()
argparser.add_argument("--display", help = "X11 DISPLAY to use", required = True)
argparser.add_argument("--address", help = "IP address to check", required = True)
args = argparser.parse_args()

# Set DISPLAY
os.putenv("DISPLAY", args.display)

# Check to see if machine is still up
def ping(address):
	proc = subprocess.run(["ping", address, "-c", "1", "-W", "1"], stdout = subprocess.DEVNULL)
	if proc.returncode > 0:
		return False
	else:
		return True

# Handle machine being down
def on_down():
	subprocess.run(["xset", "dpms", "force", "off"])

# Handle machine returning
def on_up():
	subprocess.run(["xset", "dpms", "force", "on"])

# Machine watcher thread
def watch_machine(address):
	last_awake = True

	while True:
		time.sleep(1)

		# Ping to see if the macheen is up
		is_awake = ping(address)

		# Avoid continously running the handlers if we don't need
		if is_awake == last_awake:
			#print("DEBUG: Not running handlers... no activity detected")
			continue

		# Make sure we store the state
		last_awake = is_awake

		# Run the appropriate handler
		if is_awake:
			print("DEBUG: machine is up")
			on_up()
		else:
			print("DEBUG: machine is down")
			on_down()

if __name__ == "__main__":
	# Start machine watcher thread
	machine_thread = threading.Thread(target = watch_machine, args = (args.address,), daemon = True)
	machine_thread.start()
	machine_thread.join()
